//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserTestWithReactHooks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string UserFullName { get; set; }
        public System.DateTime DOJ { get; set; }
        public string UserEmail { get; set; }
        public string UserProfile { get; set; }
        public string UserPassword { get; set; }
    }
}
